### ISSUE TITLE
自分が投稿した作品は削除できる

### ISSUE THREAD

**Issue by hirohito** [hirohito/foriio#117]
これはちょっと相談しなければいけないのですが、ツイッターで

kanatrier: @foriio_official 素晴らしいサービスをありがとうございます、今のところひとつ要望を上げるとすれば投稿の削除機能ですね。私がきちんと調べられていないのかもしれませんがデリートを選択するとcollaboratorの名前だけ消えて一度投稿してしまった物は残ってしまうので

というフィードバックをもらったので、確かに削除できた方が良いと思っているのですが、foriioは基本的に作品を複数人で所有するような形になっています。なので、一人が消したら全員消えてしまうというのはやってはいけない気がしています。

今回のユーザーさんの場合は、上記のようなコラボレーターが数人いる状態ではなく、自分一人の作品だから作品ごと削除できるようにするというのはわかります。要らないのがずっとforiio上にあるのはよろしくないので。なのでコラボレーターが1人の場合は作品を投稿したユーザーが、作品を丸ごと削除できるようにできたら良いかなと思っていますが、どうですか？

**Comment by hineltjar** [comment]
コラボレーターが1人のときは削除にしましょう 👍

**Comment by hirohito** [comment]
ありがとうございますー。
とりあえず現状はそういう対応でお願いします！

**Comment by hirohito** [comment]
@hineltjar これもそろそろ対応できると嬉しいですー！
