### ISSUE TITLE
Top pageのlikeボタンが押せない

### ISSUE THREAD

**Issue by hirohito** [hirohito/foriio#124]
トップページのlikeボタンが押しても反応しなくなっていました。

**Comment by hineltjar** [comment]
@hirohito こちらで確認したところ反応するようです。ウェブコンソールに何かエラー出てないか確認お願いします。

**Comment by hirohito** [comment]
@hineltjar Chromeに入れてたプラグインが悪さしてたみたい...！ありがとうございます。

**Comment by hineltjar** [comment]
b!
