### ISSUE TITLE
ユーザーは自分のどの作品を公開するかを管理することができる

### ISSUE THREAD

**Issue by hirohito** [hirohito/foriio#131]
昨日の打ち合わせで話した仕様です。
ーーー
foriioのように手軽にポートフォリオを作りたいユーザーの存在は確認できたが、そう言ったサービスの使いやすさや、自身とクライアントの契約上の都合など、様々な理由でまだアクティベーションまで行けていない（作品の投稿まで）と思われる。

仮説：ユーザーは自身のどの作品を公開するか管理したいと思っている。どの作品をどのクライアントに見せるか、もしくは自分のポートフォリオは限定公開に抑えたいと思っているユーザーが一定数いる。

解決策：ユーザーが自分がタグ付けされた作品を、個別に公開・非公開の設定をすることができる。非公開に設定されたものはログインしていないユーザーからは見れない。また同じく枠品の詳細ページにもそのユーザーのタグは表示されない。

ログインしているユーザーは非公開含むすべての作品を見ることができる。
また、ユーザーは限定アドレス（自分のページのアドレスの後ろにTokenがついようなもの）を発行することができ、そのアドレスを通すとその人の非公開の作品も閲覧することができる。

また、その限定アドレス経由で作品ページを見ると、非公開設定をしたユーザー自身がタグ付けされているを見える。

**Comment by hineltjar** [comment]
- [ ] ユーザーは作品との繋がりについて、公開/非公開を設定できる
- [ ] ゲストは作品ページで、作品と非公開の繋がりを持つユーザーを閲覧できない
- [ ] ゲストはユーザーページで、非公開の繋がりを持つ作品を閲覧できない
- [ ] ユーザーはすべての作品を閲覧できる
- [ ] ユーザーは非公開の繋がりをもつ作品の閲覧権限を持つURLを発行できる
  - [ ] 当該URL経由で作品ページを閲覧すると、非公開の繋がりを持つユーザー(当該URLのオーナーのみ)を閲覧できる


- users/show
- works/show
- user.rb
- collaborator.rb
- token発行 / url生成
- db migration

**Comment by hineltjar** [comment]
- [ ]
