### ISSUE TITLE
ゲストが見ているページでの、新規登録への誘導になるきっかけを作る

### ISSUE THREAD

**Issue by hirohito** [hirohito/foriio#148]
ゲストがユーザーページを見ている時のLog in / Registerボタンの文言を変更

**Comment by hineltjar** [comment]
こちらはフロントだけ？ @hirohito が自分でやる？
ちなみにフロントも振ってくれるならぜんぜんこちらで請け負います。

**Comment by hineltjar** [comment]
workページで、

- ユーザーには「そのユーザーが他に登録している作品」と「人気の作品(Like数)」
- ゲストには「foriioを紹介する用のpartial」を表示する
