### ISSUE TITLE
新規登録ユーザーがサービスの内容を簡単に理解できる

### ISSUE THREAD

**Issue by hirohito** [hirohito/foriio#149]
＊トップページの改善
＊ログイン後のチュートリアル的な要素

**Comment by hineltjar** [comment]
@hirohito 
これも具体的な案があれば見積もり出します。
なんとなくtour的な感じでやるのかと思ったけどどうなんだろう。

**Comment by hineltjar** [comment]
- modalはhirohitoさん作る

新規登録後に、ステップ式のチュートリアルモーダルを出す
