### ISSUE TITLE
招待されたユーザーがforiioに登録するメリットを理解出来る

### ISSUE THREAD

**Issue by hirohito** [hirohito/foriio#150]
＊招待されたアドレスを踏んだ時のファーストビューでサービスを理解してもらう
＊チュートリアル要素

1 : 招待アドレスを踏んだユーザーは、
＊追加されたワークカード
＊ウェルカム用文言
＊サインアップを促す文言
＊サインアップボタン
で構成されたページにたどり着く

２：サインアップを押したら、サインアップフォームの上にforiioのメリットが端的にわかるものが表示されたページに飛び、foriioの特徴を理解した上で登録することができる。

**Comment by hineltjar** [comment]
@hirohito 

ここのチュートリアル要素って、こちらで実装すべきポイントってありますか？
具体的にこういうことしたい、っていうのを教えてもらえたら見積もります！

**Comment by hineltjar** [comment]
```
  match 'users/:id/token/:access_token', to: 'users#show_via_token', via: [:get], as: :user_show_via_token
  resources :users do
    match '/token/:uuid', to: 'users#new_via_token', via: [:get, :post], as: :registration_token
  end
```

が競合してる？
