### ISSUE TITLE
ユーザーはforiio内で質の高い作品に出会うことができる

### ISSUE THREAD

**Issue by hirohito** [hirohito/foriio#152]
＊ログイン後のindexにてRecentだけでなくFeature(もしくはPick up, Hot等)された作品の一覧を見ることができる。

**Comment by hineltjar** [comment]
@hirohito 

pickup, hotのロジック次第で工数変わる感じです。

1. ピックするworkのidをコードにベタ書き
2. 週間や月間などの期間を指定して、star数, pv数などで並び替えるなど、何らかのロジックでworkの一覧を取得する
3. ピックするworkのidを、管理画面を経由していつでも指定できる形にする

思いつく限りではこんな感じで、1~3の順に工数が上がります。

**Comment by hineltjar** [comment]
1.で。
