### ISSUE TITLE
users, worksページのmeta tagをページの内容に合わせて設定する

### ISSUE THREAD

**Issue by hineltjar** [hirohito/foriio#19]
https://github.com/hineltjar/foriio/pull/18

**Comment by hineltjar** [comment]
- Twitter card
- facebook ogp

```
hirohito [12:25 PM]  
外部でシェアした時に、タイトルやサムネイルが適切な状態にしたい。
```

**Comment by hirohito** [comment]
作品ページをシェアした場合は、ogp画像で作品の最初の１枚目の画像が。
ユーザーページがシェアされた場合はogp画像でユーザーのアイコン画像が表示されるように。
