### ISSUE TITLE
ユーザーは自分の作品がどれだけ注目されているか知ることができる(view)

### ISSUE THREAD

**Issue by hirohito** [hirohito/foriio#90]
＊作品のView数を表示

**Comment by hineltjar** [comment]
- https://github.com/charlotte-ruby/impressionist

**Comment by hineltjar** [comment]
# view
- works/show

# controller
- works/show

# other
- add gem
- migration
- mod model

**Comment by hirohito** [comment]
本番環境で反映を確認しました。クローズします！ありがとうございます。
