### ISSUE TITLE
作品を簡単に外部にシェアすることができる。

### ISSUE THREAD

**Issue by hirohito** [hirohito/foriio#91]
SNSシェアボタンを設置

**Comment by hirohito** [comment]
今確認したんだけど、ワークページをシェアしてもクリックした人がログインしていないと「something went wrong」になってしまいますね。。

**Comment by hineltjar** [comment]
まじですか。確認します。

**Comment by hineltjar** [comment]
修正しました！確認お願いします

**Comment by hirohito** [comment]
確認しました！ありがとうございます！
