### ISSUE TITLE
ユーザーは自分の作品が評価されているか分かる(like数)

### ISSUE THREAD

**Issue by hineltjar** [hirohito/foriio#93]
- ♡ボタンを設置

```
Likeした時は二種類あると思ってて
1 : 友人知人のクリエイターへのラブコール
2 : 素晴らしい作品をわけてとっておきたい、すぐに見返せる場所に置きたい

[12:38]  
Likeされたってのは一覧はなくてよくて、作品にそれぞれトータル何likeか表示されてれば良いかと。あとは通知で誰か何をlikeしてくれたか。そしてそれがメールで通知される？
```

**Comment by hineltjar** [comment]
# view
- users/show(自分が過去にlikeした作品一覧)
- works/show

# controller
- users/show
- works/show
- likesController
  - create
  - destroy

# model
- likes

# others
- migration
- routes

**Comment by hirohito** [comment]
ここでの書き込みが遅れたけど、実装確認しました。ありがとう！
