### ISSUE TITLE
ユーザーはほかの誰かが自分にアクションを取ったことが分かる

### ISSUE THREAD

**Issue by hineltjar** [hirohito/foriio#94]
- 通知機能
- 現在想定されているのはworksへのlike
- ヘッダーに表示
- メールで送信

**Comment by hineltjar** [comment]
# view
- layouts/header
- users/show

# controller
- likesController
- applicationController

# model
- like

# others
- actionMailer

**Comment by hineltjar** [comment]
- 何件きたか数値出さなくていいと思ってる
- ベルアイコンの右上に赤いマークとか付ける（マーク用のdom用意）

**Comment by hirohito** [comment]
こちらも実装確認しました。ありがとう。
